<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyBestBlog.Core\MyBestBlog.Core.csproj" />
    <ProjectReference Include="..\MyBestBlog.Infrastructure\MyBestBlog.Infrastructure.csproj" />
  </ItemGroup>

</Project>
